version: '3.7'

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - WEB_CONCURRENCY=0
      - RAILS_MAX_THREADS=5
      - CONNECTION_POOL=15
      - RUBY_YJIT_ENABLE=1
      - DATABASE_URL=postgres://postgres:password@localhost/
      - PORT=8081
      - RAILS_ENV=production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8081/clientes/1/extrato || exit 1
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 40s
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '100MB'
  api02:
    <<: *api
    hostname: api02
    environment:
      - WEB_CONCURRENCY=0
      - RAILS_MAX_THREADS=5
      - CONNECTION_POOL=15
      - RUBY_YJIT_ENABLE=1
      - DATABASE_URL=postgres://postgres:password@localhost/
      - PORT=8082
      - RAILS_ENV=production
    healthcheck:
      test: curl --fail http://localhost:8082/clientes/1/extrato || exit 1
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 40s
  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '50MB'
  postgres:
    image: postgres:16-alpine
    command: 'postgres -c checkpoint_timeout=1000min -c max_connections=100 -c shared_buffers=380MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    network_mode: host
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '300MB'
    volumes:
      - ./config/setup.sql:/docker-entrypoint-initdb.d/01-setup.sql:ro
      - type: tmpfs
        target: /var/lib/postgresql/data